function R = R_euler(phi, theta, psi, mode)
% Roll, pitch, yaw



%Matriz de transformacion homogenea de Denavit-Hartemberg
% syms theta d a alpha

%     syms phi theta psi real

    rot_X = [1 0 0;...
        0 cos(phi) -sin(phi);...
        0 sin(phi) cos(phi)];
    rot_Y = [cos(theta) 0 sin(theta);...
        0 1 0;...
        -sin(theta) 0  cos(theta)];
    rot_Z = [cos(psi) -sin(psi) 0;...
        sin(psi) cos(psi) 0;...
        0 0 1];
    
%     ZYZ
if mode == 1
    rot_Z = [cos(phi) -sin(phi) 0;...
            sin(phi) cos(phi) 0;...
            0           0      1];   
    rot_Y = [cos(theta) 0 sin(theta);...
            0           1           0;...
            -sin(theta)  0   cos(theta)];
    rot_ZZ = [cos(psi) -sin(psi) 0;...
             sin(psi) cos(psi) 0;...
             0          0       1];   
    
    R = rot_Z*rot_Y*rot_ZZ;    
%     R = simplify(R);
else  %XYZ  
    R = rot_Z*rot_X*rot_Y;
%     R = simplify(R);
end